In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print (torch.__version__)

2.9.0


In [8]:
## intro to tensors
## Scalars

scalar = torch.tensor(7)
print(scalar)

scalar.ndim
scalar.item()

tensor(7)


7

In [13]:
vector = torch.tensor([7,7])
print(vector)
vector.ndim
vector.shape


tensor([7, 7])


torch.Size([2])

In [18]:
MATRIX = torch.tensor([[[1,2,3],
                        [6,5,4],
                        [8,9,10]]])

MATRIX.ndim
MATRIX.shape

torch.Size([1, 3, 3])

In [10]:
RAND_TENSOR = torch.rand(10,10,10)
RAND_TENSOR.ndim
RAND_TENSOR.shape, RAND_TENSOR.dtype

(torch.Size([10, 10, 10]), torch.float32)

In [19]:
zerosts= torch.zeros(size=(3,4))
zerosts

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
onets = torch.ones(size=(3,5))
onets,onets.dtype

(tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]),
 torch.float32)

In [ ]:
rangeItTs=torch.arange(start=0, end=10, step=1)
rangeItTs
# multi dimensional range tensor?

1

In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [14]:
## multiplication 

float_16_tensor = torch.tensor([2, 4, 24],
                               dtype=torch.int, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_16_tensor.shape, float_16_tensor.dtype, float_16_tensor.device


tensor_result = float_16_tensor * float_32_tensor
tensor_result


tensor([  6.,  24., 216.])

In [18]:
tensor_mult = torch.tensor([1,2,4]) * 10
tensor_mult

tensor_mult_rand = torch.rand(2,4)
print(tensor_mult_rand)
tensor_mult_rand * 10

tensor([[0.0920, 0.1573, 0.9966, 0.3143],
        [0.5438, 0.7797, 0.0114, 0.9549]])


tensor([[0.9201, 1.5728, 9.9662, 3.1426],
        [5.4381, 7.7970, 0.1136, 9.5485]])

In [13]:
tmult1 = torch.rand(3,2)
tmult2 = torch.rand(2,2)

torch.matmul(tmult1,tmult2)


tensor([[0.1297, 0.3237],
        [0.6144, 0.7126],
        [0.4011, 0.4408]])

In [41]:
tmult6 = torch.tensor([[1,2],
                        [2,3],
                        [5,6]])


tmult7 = torch.tensor([[11,42],
                        [23,32],
                        [45,56]])



torch.matmul(tmult6.T, tmult7)




tensor([[282, 386],
        [361, 516]])

In [46]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=4) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.3378, 0.6147, 0.7451, 0.6186],
        [4.5928, 1.5825, 0.7206, 0.7607],
        [6.8478, 2.5503, 0.6961, 0.9027]], grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 4])


In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)

print(f"Minimum: {x.min()}")
print(x.max(), x.type(torch.float32).mean(), x.sum())



Minimum: 0
tensor(90) tensor(45.) tensor(450)


In [15]:
y = torch.arange(1.,8.)

print(y)

y_reshaped = y.reshape(1,7)
y_reshaped, y_reshaped.shape


tensor([1., 2., 3., 4., 5., 6., 7.])


(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [17]:
y_stacked = torch.stack([y,y,y,y], dim=0)
y_stacked

y_squeezed = y_reshaped.squeeze()
y_squeezed, y.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [20]:
permute_y = torch.rand(size=(224, 224, 3))
permuted_y = permute_y.permute(2,0,1)
permuted_y.shape

torch.Size([3, 224, 224])

In [7]:
RANDOM_SEED = 54
torch.manual_seed(seed=RANDOM_SEED)
new_x = torch.rand(3,4)
print(new_x)

torch.random.manual_seed(seed=RANDOM_SEED)
new_y = torch.rand(3,4)

print(new_y)

tensor([[0.5668, 0.6469, 0.9893, 0.6443],
        [0.3284, 0.8259, 0.6804, 0.4878],
        [0.2030, 0.5597, 0.0477, 0.1639]])
tensor([[0.5668, 0.6469, 0.9893, 0.6443],
        [0.3284, 0.8259, 0.6804, 0.4878],
        [0.2030, 0.5597, 0.0477, 0.1639]])
